# Default Configuration for Text Generation Model

# Data parameters - Optimized for GPU power
sequence_length: 100
test_size: 0.2
random_state: 42

# Model parameters - Optimized for GPU utilization
embedding_dim: 256
hidden_dim: 512
learning_rate: 0.01
epochs: 200
batch_size: 128

# Text generation parameters
temperature: 0.8
generation_length: 200

# Training
verbose: true
save_model: true
model_path: "model/text_generation_model.npz"

# Logging
log_file: "training.log"
